from firebase_functions.params import StringParam

PROJECT_ID = StringParam("PROJECT_ID").value
LOCATION = StringParam("LOCATION").value
V1_API_ROOT = StringParam("V1_API_ROOT").value
V2_API_ROOT = StringParam("V2_API_ROOT").value
V3_API_ROOT = StringParam("V3_API_ROOT").value

OPENAI_KEY = StringParam("OPENAI_KEY").value
YOUTUBE_TOKEN_ALT = StringParam("YOUTUBE_TOKEN_ALT").value
YOUTUBE_TOKEN = StringParam("YOUTUBE_TOKEN").value
SONGSTATS_API_KEY = StringParam("SONGSTATS_API_KEY").value


SQL_USER = StringParam("SQL_USER").value
SQL_PASSWORD = StringParam("SQL_PASSWORD").value
SQL_DB = StringParam("SQL_DB").value
SQL_INSTANCE = StringParam("SQL_INSTANCE").value
API_KEY = StringParam("API_KEY").value


SPOTIFY_CLIENT_ID = StringParam("SPOTIFY_CLIENT_ID").value
SPOTIFY_CLIENT_SECRET = StringParam("SPOTIFY_CLIENT_SECRET").value
SPOTIFY_ALT_CLIENT_ID = StringParam("SPOTIFY_ALT_CLIENT_ID").value
SPOTIFY_ALT_CLIENT_SECRET = StringParam("SPOTIFY_ALT_CLIENT_SECRET").value
SPOTIFY_USER_FACING_CLIENT_ID = StringParam("SPOTIFY_USER_FACING_CLIENT_ID").value
SPOTIFY_USER_FACING_CLIENT_SECRET = StringParam("SPOTIFY_USER_FACING_CLIENT_SECRET").value


TWILIO_VERIFY_SERVICE = StringParam("TWILIO_VERIFY_SERVICE").value
TWILIO_TOKEN = StringParam("TWILIO_TOKEN").value
TWILIO_MESSAGE_SERVICE = StringParam("TWILIO_MESSAGE_SERVICE").value
TWILIO_ACCOUNT = StringParam("TWILIO_ACCOUNT").value

AIRTABLE_TOKEN = StringParam("AIRTABLE_TOKEN").value
AIRTABLE_BASE = StringParam("AIRTABLE_BASE").value

STRIPE_KEY = StringParam("STRIPE_KEY").value
STRIPE_WEBHOOK_SECRET = StringParam("STRIPE_WEBHOOK_SECRET").value
ENV_MODE = StringParam("ENV_MODE").value