from firebase_functions.params import StringParam

PROJECT_ID = StringParam("PROJECT_ID")
LOCATION = StringParam("LOCATION")
V1_API_ROOT = StringParam("V1_API_ROOT")
V2_API_ROOT = StringParam("V2_API_ROOT")
V3_API_ROOT = StringParam("V3_API_ROOT")

OPENAI_KEY = StringParam("OPENAI_KEY")
YOUTUBE_TOKEN_ALT = StringParam("YOUTUBE_TOKEN_ALT")
YOUTUBE_TOKEN = StringParam("YOUTUBE_TOKEN")
SONGSTATS_API_KEY = StringParam("SONGSTATS_API_KEY")


SQL_USER = StringParam("SQL_USER")
SQL_PASSWORD = StringParam("SQL_PASSWORD")
SQL_DB = StringParam("SQL_DB")
SQL_INSTANCE = StringParam("SQL_INSTANCE")
API_KEY = StringParam("API_KEY")


SPOTIFY_CLIENT_ID = StringParam("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = StringParam("SPOTIFY_CLIENT_SECRET")
SPOTIFY_ALT_CLIENT_ID = StringParam("SPOTIFY_ALT_CLIENT_ID")
SPOTIFY_ALT_CLIENT_SECRET = StringParam("SPOTIFY_ALT_CLIENT_SECRET")
SPOTIFY_USER_FACING_CLIENT_ID = StringParam("SPOTIFY_USER_FACING_CLIENT_ID")
SPOTIFY_USER_FACING_CLIENT_SECRET = StringParam("SPOTIFY_USER_FACING_CLIENT_SECRET")


TWILIO_VERIFY_SERVICE = StringParam("TWILIO_VERIFY_SERVICE")
TWILIO_TOKEN = StringParam("TWILIO_TOKEN")
TWILIO_MESSAGE_SERVICE = StringParam("TWILIO_MESSAGE_SERVICE")
TWILIO_ACCOUNT = StringParam("TWILIO_ACCOUNT")

AIRTABLE_TOKEN = StringParam("AIRTABLE_TOKEN")
AIRTABLE_BASE = StringParam("AIRTABLE_BASE")
